// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz5BZDy8iq0EUTitL0w--YsPhUUvDmwLY',
    appId: '1:460189515646:web:8a7367b0b0daae7984bd2f',
    messagingSenderId: '460189515646',
    projectId: 'chat-app-50d8a',
    authDomain: 'chat-app-50d8a.firebaseapp.com',
    storageBucket: 'chat-app-50d8a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwCIn9NgWmTD2W3wa9tWFT2AlTbwKJK90',
    appId: '1:460189515646:android:6e032e8487e178f684bd2f',
    messagingSenderId: '460189515646',
    projectId: 'chat-app-50d8a',
    storageBucket: 'chat-app-50d8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDYD8AA_QE1TdHkJdpcN7PboJ5ZVt6qDE',
    appId: '1:460189515646:ios:738ad5dd0def300284bd2f',
    messagingSenderId: '460189515646',
    projectId: 'chat-app-50d8a',
    storageBucket: 'chat-app-50d8a.appspot.com',
    androidClientId: '460189515646-79k9p4v2lasl37ps4iju1rh289sesq31.apps.googleusercontent.com',
    iosClientId: '460189515646-etcb21f1pic65iohoh9j85lqb82p3adm.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
